version: "2"

services:
  web:
    build: .
    env_file:
      - .env
    command: npm start
    ports:
      - "3001:3001"
    volumes:
      - ./:/yelpCamp
    links:
      - db
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./app/db/mongo:/data/db
